### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/MicroSD-breakout-hardware-design#1]
https://github.com/SolderedElectronics/MicroSD-breakout-hardware-design/blob/232cd441842d1ecf6144b45ce8203b55e23f39ce/README.md?plain=1#L5C23-L5C139

umjesto:

https://github.com/SolderedElectronics/MicroSD-breakout-hardware-design/blob/main/OUTPUTS/V1.1.1/333050.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/MicroSD-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333050.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
